name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x setup.sh
          chmod +x build.sh

      - name: Run setup.sh
        run: ./setup.sh

      - name: Run build.sh
        run: ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist/**   # change this to where your build.sh puts files