name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run setup.sh
        shell: bash
        run: ./setup.sh

      - name: Run build.sh
        shell: bash
        run: ./build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist/**   # Change this if your build.sh outputs elsewhere